apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sqsqueues.tantona.github.com
spec:
  group: tantona.github.com
  names:
    kind: SQSQueue
    listKind: SQSQueueList
    plural: sqsqueues
    singular: sqsqueue
    shortNames:
    - sqs
  scope: Namespaced
  version: v1
