apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sqs-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sqs-operator
  template:
    metadata:
      labels:
        name: sqs-operator
    spec:
      containers:
        - name: sqs-operator
          image: tantona/sqs-operator:latest
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - sqs-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "sqs-operator"
