apiVersion: "tantona.github.com/v1"
kind: "SQSQueue"
metadata:
  name: foobar-test-2
spec:
  name: foobar-test-2
  attributes:
    VisibilityTimeout: "11202"
    MaximumMessageSize: "2028"
    MessageRetentionPeriod: "259200"
    DelaySeconds: "345"
    ReceiveMessageWaitTimeSeconds: "20"
    RedrivePolicy: |
      {  
        "deadLetterTargetArn": "arn:aws:sqs:us-east-1:960199038060:foobar1234",
        "maxReceiveCount": 25
      }
    # FifoQueue: "false"

